---
services:
  tika:
    image: ${TIKA_IMAGE:-apache/tika:latest}
    # Using the base variant for smaller image size and faster startup
    # The base variant includes core functionality for text extraction
    # Full variant is only needed for specialized OCR/image processing
    # release notes: https://tika.apache.org
    networks:
      opencloud-net:
    restart: always
    logging:
      driver: ${LOG_DRIVER:-local}

  opencloud:
    environment:
      # fulltext search
      SEARCH_EXTRACTOR_TYPE: tika
      SEARCH_EXTRACTOR_TIKA_TIKA_URL: http://tika:9998
      FRONTEND_FULL_TEXT_SEARCH_ENABLED: "true"
